[versions]
designsystem = "0.0.9"
commons = "0.6.6"
terminal = "0.7.0"
navigation = "1.2.2"
payments = "0.3.16"
charge = "0.3.14"
commonshardware = "0.2.1"
auth = "0.2.5"
transactions = "0.1.8"

[libraries]
clip-designSystem = { group = "com.payclip.blaze", name = "designsystem", version.ref = "designsystem" }
clip-navigation = { group = "com.payclip.blaze", name = "navigation", version.ref = "navigation" }
clip-terminal = { group = "com.payclip.blaze", name = "terminal", version.ref = "terminal" }
clip-commons = { group = "com.payclip.blaze", name = "commons", version.ref = "commons" }
clip-payments = { group = "com.payclip.blaze", name = "payments-lib", version.ref = "payments" }
clip-charge = { group = "com.payclip.blaze", name = "charge", version.ref = "charge" }
clip-commons-hardware = { group = "com.payclip.blaze", name = "commons-hardware", version.ref = "commonshardware" }
clip-auth = { group = "com.payclip.blaze", name = "auth", version.ref = "auth" }
clip-transactions = { group = "com.payclip.blaze", name = "transactions", version.ref = "transactions" }